---
- name: OS Hardening for Linux
  hosts: all
  become: yes
  tasks:
    - name: Disable SELinux (RedHat family only)
      selinux:
        state: disabled
      when: ansible_os_family == "RedHat"

    - name: Stop and disable firewall if present
      service:
        name: "{{ ansible_os_family == 'RedHat' | ternary('firewalld', 'ufw') }}"
        state: stopped
        enabled: no
      ignore_errors: yes

# ---------------- BACKEND ----------------
- name: Configure Backend (Netdata)
  hosts: backend
  become: yes
  tasks:
    - name: Install Netdata (only if not installed)
      shell: |
        wget -O /tmp/kickstart.sh https://get.netdata.cloud/kickstart.sh
        sh /tmp/kickstart.sh --non-interactive
      args:
        creates: /usr/sbin/netdata

    - name: Ensure Netdata runs on port 19999
      lineinfile:
        path: /etc/netdata/netdata.conf
        regexp: '^\\s*default port ='
        line: '    default port = 19999'
      notify: Restart Netdata

  handlers:
    - name: Restart Netdata
      service:
        name: netdata
        state: restarted

# ---------------- FRONTEND ----------------
- name: Configure Frontend (Nginx Proxy)
  hosts: frontend
  become: yes
  vars:
    backend_ip: "{{ hostvars[groups['backend'][0]].ansible_host | default(groups['backend'][0]) }}"

  tasks:
    - name: Install Nginx
      package:
        name: nginx
        state: present

    - name: Reset nginx conf.d directory
      file:
        path: /etc/nginx/conf.d
        state: directory
        mode: '0755'

    - name: Write clean nginx.conf
      copy:
        dest: /etc/nginx/nginx.conf
        mode: '0644'
        content: |
          user nginx;
          worker_processes auto;
          error_log /var/log/nginx/error.log warn;
          pid /run/nginx.pid;

          events {
              worker_connections 1024;
          }

          http {
              include       /etc/nginx/mime.types;
              default_type  application/octet-stream;

              log_format main '$remote_addr - $remote_user [$time_local] "$request" '
                              '$status $body_bytes_sent "$http_referer" '
                              '"$http_user_agent" "$http_x_forwarded_for"';

              access_log /var/log/nginx/access.log main;

              sendfile        on;
              keepalive_timeout 65;

              include /etc/nginx/conf.d/*.conf;
          }

    - name: Write proxy configuration
      copy:
        dest: /etc/nginx/conf.d/proxy.conf
        mode: '0644'
        content: |
          server {
              listen 80 default_server;
              server_name _;

              location / {
                  proxy_pass http://{{ backend_ip }}:19999;
                  proxy_http_version 1.1;
                  proxy_set_header Host $host;
                  proxy_set_header X-Real-IP $remote_addr;
                  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                  proxy_set_header X-Forwarded-Proto $scheme;
              }
          }

    - name: Validate nginx configuration
      command: nginx -t
      register: nginx_test
      changed_when: false

    - name: Show nginx validation output
      debug:
        var: nginx_test.stderr

    - name: Start and enable nginx
      service:
        name: nginx
        state: restarted
        enabled: yes
